name: Build and Push Docker Image

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write secret to file (for debugging only)
        run: |
          echo "DOCKER_USERNAME=${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_ID }}" > secret_output1.txt
          echo "DOCKER_PASSWORD=${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_SECRET }}" >> secret_output.txt
        # The file can be inspected in the run-time environment (not recommended in production)



      # # Step 5: Log in to Azure Container Registry (ACR)
      # - name: Log in to ACR
      #   run: az acr login --name debacrregistry --username ${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_ID }} --password ${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_SECRET }}

      # # Step 6: Pull the Docker image from Docker Hub
      # - name: Pull Docker image from Docker Hub
      #   run: docker pull debasis1999/project-work:latest

      # # Step 7: Tag the Docker image for ACR
      # - name: Tag Docker image for ACR
      #   run: docker tag debasis1999/project-work debacrregistry.azurecr.io/project-work:latest

      # # Step 8: Push the Docker image to ACR
      # - name: Push Docker image to ACR
      #   run: docker push debacrregistry.azurecr.io/project-work:latest

      # Step 9: Verify that the Docker image was built and pushed
      # - name: Verify Docker image
      #   run: docker pull debasis1999/project-work:latest