name: Azure ACR Login and Docker Operations

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.ACR_CLIENT_ID }}
      #     client-secret: ${{ secrets.ACR_CLIENT_SECRET }}
      #     tenant-id: ${{ secrets.ACR_TENANT_ID }}

      # Step 3: Login to Azure Container Registry
      - name: Login to ACR
        #run: az acr login --service-principal --username ${{ secrets.ACR_CLIENT_ID }} --password ${{ secrets.ACR_CLIENT_SECRET }}
        run: az acr login --name debacrregistry --username ${{ secrets.ACR_CLIENT_ID }} --password ${{ secrets.ACR_CLIENT_SECRET }}
      # # Step 4: Pull or push a Docker image (example)
      # - name: Build and push Docker image
      #   run: |
      #     docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-image:latest .
      #     docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-image:latest

      # # Optional: Verify image
      # - name: Verify image in ACR
      #   run: |
      #     az acr repository list --name ${{ secrets.ACR_NAME }} --output table
