name: Build and Push Docker Image

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image to Docker Hub
      # - name: Build and push Docker image to Docker Hub
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .  # Change this to root directory
      #     push: true
      #     tags: debasis1999/project-work:latest
      #     build-args: |
      #       SQL_USER_ID=${{ secrets.SQL_USER_ID }}
      #       SQL_DB_PASS=${{ secrets.SQL_DB_PASS }}
      #       SQL_DB_HOST=${{ secrets.SQL_DB_HOST }}
      #       SQL_DB_NAME=${{ secrets.SQL_DB_NAME }}
      #       SQL_DB_ENCRYPT=${{ secrets.SQL_DB_ENCRYPT }}

      # Step 5: Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
       # run: az login --service-principal --client-id ${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_ID }} --client-secret ${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_SECRET }} --tenant-id ${{ secrets.AZURE_CONTAINER_REGISTRY_TENANT_ID }}
        run: az acr login --name debacrregistry --username ${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_ID }} --password ${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_SECRET }}

      # Step 6: Pull the Docker image from Docker Hub
      - name: Pull Docker image from Docker Hub
        run: docker pull debasis1999/project-work:latest

      # Step 7: Tag the Docker image for ACR
      - name: Tag Docker image for ACR
        run: docker tag debasis1999/project-work debacrregistry.azurecr.io/project-work:latest

      # Step 8: Push the Docker image to ACR
      - name: Push Docker image to ACR
        run: docker push debacrregistry.azurecr.io/project-work:latest

      # Step 9: Verify that the Docker image was built and pushed
      # - name: Verify Docker image
      #   run: docker pull debasis1999/project-work:latest